### ISSUE TITLE
Kill the transfer after timeout  

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/AsyncStageout#4197]
Details are here https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/1931/2/1/1.html

**Comment by mmascher** [comment]
Hi,

coming back to this after I had a chat with Hassen. We found a bug (which is now understood) where files can be deleted on the destination storage, and we agreed we need a working kill in FTS ASAP. But this triggered another discussion concerning timeouts which I would like to address here.

Currently there are 2 retries in ASO and the transfer timeout for each retry is 5 hours. The cooloff time is 2 hours. This means 5 + 2 + 5 + 2 + 5=19hours in total. Given that 5 hours were not anough for FTS to transfer these small files because probably these transfer were in some queue in FTS (and the queue priority was loss after each retry), wouldn't make sense to change the ASO parameters having a longer timeout with less retries? What about Something like 1 retry and 9 hours of timeout which means: 9 + 2 + 9 = 20 hours?

Thoughts?

**Comment by TonyWildish** [comment]
I can see arguments for or against what you propose, but I guess we need data to settle it. Do we know what fraction of the time transfers succeed on the first retry after a failure, and what fraction of time transfers succeed on the second retry?

If the success rate is very high on the first retry and very low on the second then we could drop the second, since it's not helping much.

If the success rate is only fairly high on the first retry and still quite high on the second then your strategy makes sense. It implies that the first retry is coming too soon.

OTOH, it might be better to invert the timeout/cooloff intervals. Time-out the transfer after 2 hours, not 5, and give a 5-hour cooloff, not 2. That gets the job out of the FTS queue sooner, and for longer, which may help.

**Comment by mmascher** [comment]
Agreed, let's prepare some numbers and then do some evaluations. Blindly changing these settings without a metric to evaluate their effectiviness is not going to help us. @jmarra13 is already preparing a kibana page for CRAB3 and ASO, maybe we can work with him to decide what to monitor exactly.

About inverting cooloff and timeouts, for the moment the FTS transfer are not removed from the FTS queue once the timeout is reache, so I don't think it is going to help. I know Hassen is in contact with FTS developer to see if they can implement a kill that would work for us in FTS. Then we can re-evaluate this.

**Comment by HassenRiahi** [comment]
Within this patch https://github.com/dmwm/AsyncStageout/pull/4405, this issue will be fixed since the transfers will be killed by FTS after a timeout. I am summarizing this ticket in a new one to agree on best timeout values.
