### ISSUE TITLE
Have fatal error in ASO

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4321]
Maybe this list of Fatal errors will increase later :
"Failed to retrieve proxy"
"Failed to make delegation for  FTS"

**Comment by HassenRiahi** [comment]
I would not make them as fatal error since both commands could succeed in the next retry. The only fatal error that I could consider here right now is "Source file does not exist" since the next transfer retry will fail for sure. Am I wrong?

**Comment by HassenRiahi** [comment]
Another fatal error that I would consider is the job time-out. If a transfer job goes in time-out after 20 hours (configurable), it does not make sense to retry it again after 2 hours of cool-off. The user needs to wait until the transfer queue to their home site in FTS gets freed. @TonyWildish / @hernand , how sounds? or maybe an API in FTS monitoring that retrieves an estimation of the latency of the transfer could help here. The CRAB job will not be submitted to avoid wasting the resources if we know in advance that the transfer will fail for timeout.

**Comment by TonyWildish** [comment]
I'd check to find out how many times that 20-hour timeout is hit first, and see if you can find the reasons why. My bet is that it's not just long queues to destinations (most T2's are hardly ever that busy), it's probably due to a failure that needs manual intervention.

If that's true then a 20-hour timeout an 2-hour cooloff doesn't make sense. Better to have a 5-hour timeout and a 20-hour cooloff instead. I.e. let the user know early that there's a problem, so they can decide to do something else, and then wait a long time for someone to fix it.

**Comment by hernand** [comment]
Given the expected maximum latency of few hours to deliver user files, if there is a problem, the user needs to know what is going on in that time scale of few hours. The question is whether ASO is able to know what is going on and report back to the user ... It would be great if the user could know since when the transfer is scheduled, what is the time left for the timeout, the time that the transfer will stay in cool-off after timeout, and the number of retries left. Based on that information the user might decide to abort the job, or wait for the transfers to retry. I would set a too large cool-off.

**Comment by TonyWildish** [comment]
I don't think ASO can know _why_ there's a problem, but it can atl least flag slow transfers or jobs that have been queued for a long time. Then it's up to the transfer-team or the usual techniques to find out what the problems are between sites.

**Comment by HassenRiahi** [comment]
> I'd check to find out how many times that 20-hour timeout is hit first, and see if you can find the reasons why. My bet is that it's not just long queues to destinations (most T2's are hardly ever that busy), it's probably due to a failure that needs manual intervention.

So far, the main reason noticed causing the timeout are a bad configuration of the channel causing a long queue or the channel is correctly configured but load on the channel is really high making the queue long.  

>If that's true then a 20-hour timeout an 2-hour cooloff doesn't make sense. Better to have a 5-hour timeout and a 20-hour cooloff instead. I.e. let the user know early that there's a problem, so they can decide to do something else, and then wait a long time for someone to fix it.

Maybe at submission time of the task, the FTS latency API could be queried to give users feedbacks on the expected latency and let him deciding whether submitting CRAB jobs or not. If the latency expected is high and he decides to not submit, suggest him to contact his site admin/the transfer team. 

>It would be great if the user could know since when the transfer is scheduled,

It is available in the job monitoring. Various FTS status (submitted, active, finished/failed) for the various retries of the outputs are reported back to the job monitoring. 
 
>what is the time left for the timeout, the time that the transfer will stay in cool-off after timeout, and the number of retries left.

Currently in the postjob log, the user could know if their outputs are in cool-off or on-going. Maybe adding in the same place, the time left for the timeout and the number of retries left.
 
> Based on that information the user might decide to abort the job, or wait for the transfers to retry. I would set a too large cool-off. 

Maybe the cool-off period could be set depending on the failure reason. If the failure reason for example is is "FTS unreachable". Most likely it is a temporary issue or a service upgrade and in this case the cool-off for 2 hours should be ok I think. In case of time-out, 20h, maybe it is the case simply to kill the files and report the reason back to users.

> but it can atl least flag slow transfers or jobs that have been queued for a long time.

It could be included here https://github.com/dmwm/AsyncStageout/issues/4370 so that transfer team could spot it and check accordingly if there is an issue.

**Comment by hernand** [comment]
I think the important thing is to provide the necessary information to users and operators so that they can know what is going on. Now users can follow the transfers via the FTS  monitoring following the links in the dashboard, right? Maybe exposing the ASO transfer logs in some way, similiarly to what PhEDEx does, would be good. By the way, how do operators check transfer problems in ASO? Looking directly into the logs of the service?

**Comment by HassenRiahi** [comment]
> Now users can follow the transfers via the FTS monitoring following the links in the dashboard, right?
Yes!
 
>  Maybe exposing the ASO transfer logs in some way, similiarly to what PhEDEx does, would be good.
The transfer status/errors are also reported in the postjob log. 

> how do operators check transfer problems in ASO? Looking directly into the logs of the service?
ASO monitoring/FTS dashboard/logs of the service

**Comment by juztas** [comment]
We check here : https://cmsweb.cern.ch/aso-monitor/index.html and in case of red - https://cmsweb.cern.ch/couchdb/_utils/database.html?asynctransfer/_design/AsyncTransfer/_view/TransfersByFailuresReasons
But this view I wanted to rewrite (split date into separate columns). 
Also sometimes this : http://dashb-fts-transfers.cern.ch/ui/#activity=%28ASO%29&date.interval=1440&grouping.dst=%28site%29&p.grouping=src&server=%28lcgfts3.gridpp.rl.ac.uk%29&tab=history_plots&vo=%28%29
ASO logs of each component;
Also checking in glidemon sorting by failed jobs (Last 1 day), but this also has  some site problems, user config problems, crab3, transfers...

**Comment by hernand** [comment]
ok, thanks for the links. I forgot, does the "acquired" status in the aso-monitor mean that the transfer has been submitted to FTS but has not finished yet? One can then check for a significant increase in this number to spot a problem.

Any plan to use the kibana CERN monitoring system to display some appropriate metrics about the health of ASO and set monitoring alarms? I think some simple interface for operators and CRC shifters would be good.

**Comment by juztas** [comment]
Just a comment. As I noticed now that we have some red plots : https://cmsweb.cern.ch/aso-monitor/index.html
Checked glidemon by failures and this user quota exceeded http://glidemon.web.cern.ch/glidemon/user.php?userid=1212&range=1day&type=crab3

And as @HassenRiahi wrote, we can see this in Postjob log http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms0114.cern.ch/mon/cms1555/150209_193701_crab3test-5:neminize_crab_SingleEl_Run2012C_part1_v1/postjob.244.0.txt
```
-----> ASO log start -----
TRANSFER  globus_ftp_client: the server responded with an error 500 Command failed. : open/create error: Function not implemented   
<----- ASO log finish ----
```

**Comment by juztas** [comment]
It would be great to move everything to Kibana, I wrote a beginning for TaskWorker https://github.com/dmwm/CRABServer/pull/4652 and @jmarra13 is working further on this https://github.com/dmwm/CRABServer/issues/4658 Will create a new ticket for ASO there we can collect all information which we want to send to Kibana

**Comment by hernand** [comment]
One question about the postjob  log. It shows that it took more than 6 hours to fail the transfer. I guess this is because there are retries and a cool-off (2h) between retries. Would it be possible to show in the postjob log a message about each transfer failure->cool-off->retry so that the user can know what is going on? For example: transfer failed with error "blah". Going to cool-off for N hours and then retry (M retries left).

**Comment by mmascher** [comment]
@juztas says it's done
