### ISSUE TITLE
High memory usage of ASO

### ISSUE THREAD

**Issue by mmascher** [dmwm/AsyncStageout#4443]
See  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/930.html

```
>free -m
total       used       free     shared    buffers     cached
Mem:         64322      63929        392          0        123        549
-/+ buffers/cache:      63256       1065
Swap:        32223      32223          0
```

and that's what I saw in the DBSPublisher log:

```
self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by HassenRiahi** [comment]
It seems that the DBSPublisher component was causing the huge usage of the memory. The memory usage is now stable. Since the files metadata retrieved from CS is loaded in memory, it could be that a user has abused of the system and requested the publication of a huge number of files.  Debug is on-going.

**Comment by HassenRiahi** [comment]
A command restarting the DBSPublisher component has been added in crontab to release the memory until the issue will be understood and fixed.

**Comment by HassenRiahi** [comment]
The RAM/swap is filled with the metadata retrieved from CS and for some reasons it is not released.

**Comment by belforte** [comment]
obsolete

**Comment by dciangot** [comment]
As discussed yesterday, this issue looks like never really solved.

**Comment by belforte** [comment]
@mmascher can you fish out the thread on the memory consumption issue in crab server and the discussion that was already done there about python not releasing memory ? As discussed in yesterdays meeting this is likely the problem here, and it is more general affecting also TW. So we could try for a combined undertstanding and solution, and involve other python experts as needed.

**Comment by mmascher** [comment]
Hi @belforte , I think this is what we are looking for https://github.com/dmwm/CRABServer/issues/5071

And this is what I wrote to simulate the behavior of the REST code: https://github.com/dmwm/CRABServer/issues/5071

**Comment by belforte** [comment]
thanks @mmascher I feel like I never read that. After reading, I suspect that we may need to get Eric and Valentin involved. Since this time it may not be as simple as "do not expand the dictionaries". Maybe DBS should return more compact data structure that we expand a bit at a time (for TW) or can accept a more compact lumi list (for ASO publivation) but solution may need changes outside CRAB, or simply help from others.
First is to figure our when exactly our memory usage jumps. It is clearly rare in TW but very frequent in ASO.

**Comment by mmascher** [comment]
I wonder if we can optimize the code here https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/PublisherWorker.py#L665 so that less things are loaded in memory. It looks to me we use one `toPublish` item at a time here: https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/PublisherWorker.py#L1172 . IMHO it is where the memory usage is high. What do you think @dciangot?

The other thing to check is if we are actually using `jemalloc`which helped on CMSWEB (in addition to our code optimization). It looks to me it is not used in the TW https://github.com/cms-sw/cmsdist/blob/comp_gcc493/crabtaskworker.spec , but is used in ASO https://github.com/cms-sw/cmsdist/blob/comp_gcc493/asyncstageout.spec#L16
But I don't remember if that `Requires` is enough to activate it.

**Comment by belforte** [comment]
I suspect that those `toPublish` being iterated upon are datasets, so a rare case with very low 
multiplicity. Let's find a reproducible situation where memory usage explodes, then we can find out 
for sure.

**Comment by belforte** [comment]
this i a very serious problem now
https://cms-logbook.cern.ch/elog/Analysis+Operations/1593
see memory usage today on vocms0125 below:
![screenshot from 2017-07-23 11-28-42](https://user-images.githubusercontent.com/1837785/28498441-e3c262b0-6f9d-11e7-9e19-05066d400290.png)

**Comment by belforte** [comment]
discussed with @dciangot on chat:
things got out of hand since last upgrade. We fear it is the new, expaned, dictionaries with evts/lumi. Do we go from a compact `run:1,lumis:1-100`  to 100 triplets ?
Only sure thing is that swap usage (see above picture) is reset every 2h at the 21min mark when a crontab restarts DBS Publisher.

Action plan:
1. add RAM monitoring to Publisher, as done by Marco for TW in the past so we can check usage by user/block
2. investigate jmalloc (need @mmascher for help).
3. Once we understand more, we will plan more.
