### ISSUE TITLE
Change logging to rotate every day

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4495]
Logging function can be specified to rotate every day and append date into the log file. It would be much easier to debug.

Please see: https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2509.html

**Comment by belforte** [comment]
it is more basic than that. stderr is not rotate at all now. And I see in it apparently same messages as in ComponentLog.

**Comment by juztas** [comment]
https://github.com/dmwm/AsyncStageout/issues/4275

**Comment by belforte** [comment]
by the way, in spite of what written in those closed issues (#4275 above and references wherein), stdout.log still does not have timestamps

also comments in those closed issues suggest that stderr is simply a concatenation of all rotated away logs, which I do not know what gains wrt to keeping them around in zipped format.

**Comment by juztas** [comment]
Mh.. This should work: https://docs.python.org/2/library/logging.handlers.html#timedrotatingfilehandler

**Comment by dciangot** [comment]
Thinking about a solution today, I found different proposals that I would like to share with you.

Right now the only implementation of a rotation is what defined here (https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Agent/Harness.py#L137), basically 3 backups rotated every 1GB. It is clear that for our use case that is pretty much useless.

So, the first clean proposal is:
-- patch in WMCore the Harness.py, with a rotation by time (every 4 days and 7 or 10 backup files?). Although I cannot say right now where and if that logging is used somewhere else, so it is not going to be of easy and fast implementation, I'm afraid.

The second proposal:
-- patching ASO in this way (https://github.com/dciangot/AsyncStageout/commit/67011cb4bb567a9a82f3a440784d4d23e68e66a2), adding a rotating log "CompLog". In that case we can adjust the parameters whenever we want to.
The con here is that first I'm not sure how and if we can switch off the wmcore "ComponentLog" w/o touching the same file proposed above, second we may also want to remove the stderr log and keep older backup files info somewhere automatically (not a big deal in case).

The third proposal is a dirty one, but really fast to implement
--  create a cron to rotate stderr log. But first we need to add timestamp there (still need to evaluate how to) and then it will be stacked  up to the ASO deployment operations that are already many.

What do you think?
 I'm elaborating still, so if anyone has a cleaner solution in mind, well please share it. I would like to solve this point asap, since it is already here for way too much time imo.

**Comment by belforte** [comment]
had a chat on skype with @dciangot . We agreed to go for second proposal (already implemented !) and use logrotate to control CompLog and to squeeze stderr. No need to touch the current WMCore actions, it creates 3GB of logs we do not care for, too bad and so long.

**Comment by belforte** [comment]
see 
https://github.com/dmwm/AsyncStageout/pull/4501#issuecomment-216135621

**Comment by dciangot** [comment]
Now done for every ASO log on machine with a crontab. Working since months. Please close it.

@belforte @mmascher

**Comment by belforte** [comment]
Now done for every ASO log on machine with a crontab. Working since months
